"""composite index on calendar_events user/start

Revision ID: 9d29d16038a5
Revises: a7a053b8358b
Create Date: 2026-07-05 13:38:38.717768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d29d16038a5'
down_revision: Union[str, None] = 'a7a053b8358b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_calendar_events_user_start', 'calendar_events', ['user_id', 'start_date', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calendar_events_user_start', table_name='calendar_events')
    # ### end Alembic commands ###
